[Issue #36] - Add rejects names beginning with -
If we are to be consistent and treat all command line arguments that
begin with - or -- as command options, we cannot allow the ADD
action to write an entry with a reference name that begins with -.
Otherwise, we would be able to park a directory with a name but
never be able to use it because
$ pd -a -n
Added: -n --> /current/working/directory
$pd -n
-n  ERROR: Unknown argument

Prevent ADD from parking a directory with a ref name beginning with
a -.

$ pd -a -n
ERROR: Reference name may not contain '/' or begin with '-'